### ISSUE TITLE
DevOps Request: Releases

### ISSUE THREAD

**Issue by jspraul** [akovacs/uploadserver#1]
This kind of tool is often needed quickly, in contrast to having nightly rust handy.

Please consider offering releases for Mac / Windows / Linux, and if you wanted to go whole-hog I don't think anyone would be upset if you offered mobile apps. (I just decided that this should be my first [Fyne](https://github.com/fyne-io/fyne) project, accessible or not.)

Thanks for your efforts and willingness to share!

PS. As seen at: https://news.ycombinator.com/item?id=29768376#29771206

**Comment by akovacs** [comment]
Thank you for your interest in the project and for filing the bug report!

I've compiled x86-64 binaries for Mac, Windows, and Linux and packaged them into a [v1.0.0 release](https://github.com/akovacs/uploadserver/releases/tag/v1.0.0).

Creating mobile app ideas is an excellent idea, perhaps I'll add that functionality in a future release when I have more time (figuring out how to build a binary that won't break across different operating system versions can be quite tricky!). It would also be nice to add support for ARM platforms such as M1 Apple Silicon, ARM Linux distributions, and ARM Windows at some point in the future, however I don't have access to Apple Silicon or Windows ARM devices at the moment.

Thanks for sharing Fyne as well, it looks like an interesting project and a really productive way to build a graphical interface! If you are not tied to Go as an implementation language, I'd also consider taking a look at [Flutter](https://flutter.dev/) since it is also cross-platform and seems to have [better accessibility support](https://docs.flutter.dev/development/accessibility-and-localization/accessibility) compared to immediate-mode GUI toolkits where [accessibility functionality might be difficult to implement](https://github.com/fyne-io/fyne/issues/1093).
